language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pash04/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pash04/react-test npm test

after_success:
  - docker build -t pash04/multi-client ./client
  - docker build -t pash04/multi-nginx ./nginx
  - docker build -t pash04/multi-server ./server
  - docker build -t pash04/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the images to docker hub
  - docker push pash04/multi-client
  - docker push pash04/multi-server
  - docker push pash04/multi-nginx
  - docker push pash04/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: Multidocker-env
  bucket_name: "elasticbeanstalk-ap-south-1-462623432869"
  bucket_path: "docker-multi"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
