version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment: 
      POSTGRES_PASSWORD: 'test'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    depends_on: 
      - api
      - client
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '8080:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /home/app/node_modules
      - ./server:/home/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=posgres
      - PGHOST=posgres
      - PGDATABASE=posgres
      - PGPASSWORD=test
      - PGPORT=5432
  client:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /home/app/node_modules
      - ./client:/home/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /home/app/node_modules
      - ./worker:/home/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379


